### PR TITLE
Allow custom name for a `foreignKey` via. parent

### PR DESCRIPTION
**Pull request by cuva**
Adds the ability to specify a custom `foreignIdKey` name when using `Builder.parent()`. One use case would be a `Category` referencing another `Category` as its parent. In that instance, changing `Category.foreignIdKey` wouldn't be the way to go as other objects may still want to reference a `Category` by its original `foreignIdKey`.

Another use case would be a `Car` referencing twice a `User`, one via `ownerId` and another via `driverId`.

```swift
category.parent(Category.self, name: Attributes.parentId, optional: true)
```

Anyhow, no breaking changes - the added parameter defaults to the same value `E.foreignIdKey`.

### CODE REVIEW

**Comment by tanner0101** [comment]
Changing the name to anything besides `Parent.foreignIdKey` will make the inverse relation (Children) not work: https://github.com/vapor/fluent/blob/88517ee7331f14595ff66b6827ea47180263fa61/Sources/Fluent/Relations/Children.swift#L27

**Comment by cuva** [comment]
Haha, was just debugging that indeed. How about adding the ability to pass a custom `foreignIdKey` when creating a `Children` - which would default to `Parent.foreignIdKey`?

If you think the use case is too restricted I'm happy to keep that as an extension in my project - otherwise, I'll push another commit soonish!

**Comment by tanner0101** [comment]
We had it that way in Fluent 1.0 and it seemed to create some confusion. The workaround now is to create a placeholder `Entity` type w/ the desired key names. This keeps both the external and internal API a lot simpler. However, if there's a use case being prevented by this approach we should reevaluate.

**Comment by LazyBoy72** [comment]
I'm interested in this issue too and I think the real use case is normally not when you have a parent/children (master/detail) relationship, but more when you are implementing a lookup table.
In Fluent model we have to use (wrongly) the parent paradigm for the lookup paradigm but in this case we are not interested in the children relationship.
Probably could be better to add a different paradigm (Lookup?) without the constraint of the reverse relation.

**Comment by tanner0101** [comment]
Moved to https://github.com/vapor/fluent/pull/251

**Pull request closed without merging**
