### PR TITLE
Generate Custom Model IDs

### PR DESCRIPTION
**Pull request by kgn**
Hey Guys,

I ran into a situation where I have a model, like an invite, that I wanted to generate a custom token for. I then wanted to use that custom token as the model's ID, similar to using a UUID. I saw there is a `custom` type for `IdentifierType` but saw now way to specify a value for an ID, perhaps I missed it...

Here's a bit of what my model looks like with this new `generateId` function I added:

```swift
final class Invite: Model {
    static let idType = IdentifierType.custom("TEXT")
    ...
    func generateId(for custom: String) throws -> Identifier? {
        let token = try URandom.bytes(count: 5).hexString
        return Identifier(token)
    }
    ...
}
```

This then allows me to look up an `Invite` with all the standard resources and auto parameter magic in vapor: `:id`.

This fork is not meant to be merged in as is, I slammed this together to prove it out in my own app's unit tests, works there. If this solution looks good to others I'll refine the code and add unit tests.

Lemme know!

### CODE REVIEW

**Comment by tanner0101** [comment]
I like this. However, the `.custom` case of the Identifier type should probably contain the closure to generate the ID. I think that would make the most sense.

**Comment by kgn** [comment]
@tanner0101 that seems like a much cleaner implementation

**Comment by kgn** [comment]
@tanner0101 please lemme know what you think of the changes I just pushed. I added the closure you suggested to `.custom`, and also added a convenience `.string` type to wrap the underlying database type.

``` swift
    static let idType = IdentifierType.string { () -> Identifier? in
        return Identifier(try URandom.bytes(count: tokenBytes).hexString)
    }
```

**Comment by tanner0101** [comment]
I think that's perfect.

**Comment by tanner0101** [comment]
However that does mean we will definitely have to wait until Fluent 3.0.

**Comment by kgn** [comment]
Cool, how far out is Fluent 3?

**Comment by tanner0101** [comment]
Nothing concrete yet, but there will likely be an update near the Swift 4 release.

**Comment by kgn** [comment]
@tanner0101 what if I added back `case custom(String)`?That way it wouldn't be a breaking change, it's just be adding new enums.

**Comment by tanner0101** [comment]
Adding a new case to a `public enum` is also a breaking change.

**Comment by kgn** [comment]
Ah, did not know that. Bummer, is that cause it breaks binary compatibility? Or can it break source compatibility?

**Comment by tanner0101** [comment]
If you are exhaustively switching over the enum in your code (no `default` case), then a new case being added will cause the "exhaustively switch or add a default case" error. Subtle but technically a breaking change. That's why we add `.unknown(Error)` cases to all of our error enums--in case we need to add a new error that wasn't previously accounted for.

**Comment by kgn** [comment]
Oh yeah, that makes sense

**Comment by tanner0101** [comment]
Custom ID types are possible in Fluent 3

**Pull request closed without merging**
