### PR TITLE
Update readme to reflect Swift 3.1 requirement

### PR DESCRIPTION
**Pull request by LuizZak**

### CODE REVIEW

**Comment by tanner0101** [comment]
swift 3.1 is not required for Fluent 1.0 (which is the latest release)

**Comment by vzsg** [comment]
But this seems to be a commit to Fluent's master, where Swift 3.1 is actually required 🤔

**Comment by tanner0101** [comment]
That's an unfortunate gray area with GitHub readmes (we're moving stuff to the docs in Vapor 2 so they can be versioned).

Since 1.0 is the latest released version, our GitHub readmes should make sense in the context of 1.0.

**Comment by LuizZak** [comment]
That makes sense, better leave it as is for now, then!.

**Pull request closed without merging**
