### PR TITLE
Suggested change to enable properties to be excluded?

### PR DESCRIPTION
**Pull request by patchthecode**
I want the migration to exclude certain properties.

Not sure if this is the best way to go about it, but could this be a possible update?

### CODE REVIEW

**Comment by patchthecode** [comment]
> Can you explain why you want that?
OK here is why I wanted to have some variables excluded from the model.

I have a model class with say 4 variables. 
I wish to have only 2 of those variables stored on the Database

```swift
final class TestModel: Content {
   var first: String         // Save on database
   var second: String   // Save on database
   var launchDataProcessor: Launcher  // This processes some data on model, but should not be stored in database
   var dataServiceTester: CustomServiceTester // This processes some data on model, but should not be stored 
}
```

I understand that in the traditional sense, a database model should only properties of the model; but this makes more sense to be this strict when referring to a database. 
A `class` however (although relating to a database model) can contain a number of other things which (in my case) helps with processing the data of the model. And makes it convenient when passing the model around.

The only problem is, every variable gets saved to the database table when only `first` and `second` is needed. So i need some way to exclude some variables from going to the database.

The pull request i provided definitely has to be improved -> eg, it should use keyPaths instead of raw strings. But i do not know how to implement this with the Vapors `ReflectedProperty` struct.

**Comment by MrMage** [comment]
Did you consider putting `first` and `second` in a separate inner wrapper struct and only persisting that struct to the database?

**Comment by patchthecode** [comment]
@MrMage I have not considered that. If this feature request is something that Vapor does not want to manage, then its ok. But I thought it would be a good idea as it was simple to implement and saves people from having to do something like that in their models.

**Comment by tanner0101** [comment]
After considering this, I think the best route for Fluent is to push users toward implementing migrations manually as much as possible. The auto migrations are nice for getting started, but in the end they are not very maintainable. 

If the automatic migration Fluent provides is not sufficient, the most maintainable path forward is to implement the migration yourself. This will save time (and confusion) later if you end up adding additional fields or constraints to your schema.

Closing this issue for now, but we can reopen if you disagree with that reasoning.

**Pull request closed without merging**
