### PR TITLE
Separate LIMIT and OFFSET output

### PR DESCRIPTION
**Pull request by natebird**
* This separation is needed for PostgreSQL compatibility. The `sql(limit)` function can't be overridden because `.count` is an internal method of `Limit`.

### CODE REVIEW

**Comment by natebird** [comment]
The question I have is whether this breaks compatibility with other drivers (MySQL, SQLite).

**Comment by tannernelson** [comment]
I think the better solution here might be to just override that method in the postgres sql serializer.

Like what is done here: https://github.com/vapor/mysql-driver/blob/master/Sources/FluentMySQL/MySQLSerializer.swift

**Comment by natebird** [comment]
It looks like the `LIMIT <value> OFFSET <value>` [syntax was added](http://dev.mysql.com/doc/refman/5.7/en/select.html) to MySQL to provide compatibility with PostgreSQL. 

SQLite [docs](https://www.sqlite.org/lang_select.html#limitoffset) also show that it supports both formats.

**Comment by natebird** [comment]
@tannernelson I can't override this function because the `Limit.count` method is internal and not accessible in the PostgreSQL library.

**Comment by tannernelson** [comment]
That's a bug that those aren't accessible. Those should definitely be public!

**Comment by natebird** [comment]
Ok, I'll open a pull request to just make them public then. :-)

**Pull request closed without merging**
