### PR TITLE
Make `BenchmarkTimestampable` care more about fractional-second parts.

### PR DESCRIPTION
**Pull request by MrMage**
See https://github.com/vapor/postgresql/pull/29.

### CODE REVIEW

**Comment by tanner0101** [comment]
@MrMage can you take a look at the merge conflict?

**Comment by MrMage** [comment]
The failure on Postgres is expected. It seems like we also need to fix the MySQL driver.

**Comment by MrMage** [comment]
Hopefully fixed MySQL: https://github.com/vapor/mysql/pull/141.

**Comment by tanner0101** [comment]
Looks like PostgreSQL is now passing as expected! However, MySQL doesn't appear to be fetching the microseconds:

```sh
/root/fluent-mysql/Packages/Fluent/Sources/FluentBenchmark/BenchmarkTimestampable.swift:40: error: FluentMySQLTests.testTimestampable : failed - fetched createdAt timestamp 1520974866.0 is more than 2ms different from expected value 1520974866.09293
```

**Comment by MrMage** [comment]
You were correct. I submitted https://github.com/vapor/fluent-mysql/pull/84.

**Pull request merged**
