### PR TITLE
save, create, and update return self

### PR DESCRIPTION
**Pull request by tanner0101**
Fixes https://github.com/vapor/fluent/issues/342

Not sure about this one as (at least from a framework perspective) this adds clutter to the code. We can discuss further in the comments below.

### CODE REVIEW

**Comment by twof** [comment]
Any reason to leave out delete?

**Comment by calebkleveter** [comment]
IMO, it doesn't clutter the code hardly at all. I think the benefits out weight the additional `transform` calls in the Fluent methods.

**Comment by tanner0101** [comment]
@twof it seems like an anti-pattern to return deleted data. afaik, you should return the `204` or `200` response.

**Comment by calebkleveter** [comment]
@tanner0101 Would it make sense to return the ID of the deleted row, or not? I could see why not, as the client should pass the ID in as a route parameter so it already knows it (`myapi.io/users/2`)

**Comment by 0xTim** [comment]
Yeah for a delete I would just return a 204

**Comment by 0xTim** [comment]
Also the ID won't be valid so there isn't much point returning that

**Comment by calebkleveter** [comment]
That would be the point, now we know what the invalid ID is. In case we are storing any ID specific data ourselves about the models from the API or something.

**Comment by vzsg** [comment]
Why blend HTTP responses with the return type of a database layer function?

**Comment by twof** [comment]
You might need access to the deleted item if you wanted to go on to query relations (children/parents) right?

**Comment by rafaelGuerreiro** [comment]
"I could see why not, as the client should pass the ID in as a route parameter so it already knows it"
Not always true. I can delete many rows based on a criteria and then, having the ID of the removed rows, I can remove these items from the UI as well.

**Comment by tanner0101** [comment]
Why not just delete all of the related items first (while you still have a valid, non-deleted model). 

Merging this as is (0xtim needs to for filming). We can continue to discuss deleted returning the model as well. We should take a look to see how other ORMs handle this if possible.

**Pull request merged**
